repos:
  # Black for auto-formatting
  - repo: https://github.com/psf/black
    rev: 23.12.1  # Check latest version
    hooks:
      - id: black
        args: ["--line-length=88"]

  # Pylint for linting all Python files
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: rye run pylint --fail-under=8.0
        language: system
        types: [python]

